name: Update Graphs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run employment-based scraping script
      run: python scrape_visa_bulletins.py

    - name: Run family-based scraping script
      run: python scrape_family_visa_bulletins.py

    - name: Run employment-based visualization script
      run: python visualize_visa_wait_times.py

    - name: Run family-based visualization script
      run: python visualize_family_wait_times.py

    - name: Commit and push changes
      run: |
        git config --local user.email "168046724+jrebull@users.noreply.github.com"
        git config --local user.name "Javier Rebull"
        # Check for changes
        if git diff --exit-code; then
          echo "No changes to commit"
        else
          git commit -am "Update graphs with latest data"
          git push
        fi
